### ISSUE TITLE
iOS vs Android status change

### ISSUE THREAD

**Issue by Aram4ik** [agilecube/Amigo#23] opened 2015-10-08 19:33 UTC
Please see video
https://youtu.be/1glJeo8-wUs

**Comment by agilecubeteam** [comment] 2015-10-12 09:55
we have tested in ios simulator (i phone 6 ( ios 8.3 version)) and its work properly. we are unable to reproduce this issue so please provide ios version and ios device in which you tested.

**Comment by Aram4ik** [comment] 2015-10-12 18:00
iOS 9.1, iPhone 6

**Comment by agilecubeteam** [comment] 2015-10-15 10:18
@Aram4ik :  our analysis says that iOS9 has just came, and people have started submitting their apps from 9/11/2015.

However, ionic is still preparing for this version of iOS. We found exact route error in which is there in ionic-iOS9 . see following blog and exact error point.

So, ionic itself is preparing for iOS9, so we have to wait till they are not giving green signal.  Share your thoughts please !!!

http://blog.ionic.io/preparing-for-ios-9

![ios9](https://cloud.githubusercontent.com/assets/14108944/10511015/1629911c-7354-11e5-9fa5-2d560cb04c26.png)

**Comment by Aram4ik** [comment] 2015-10-15 10:58
Okay, I understand. It's fine now. I can explain and we can wait. Do you know how long it takes from ionic framework to update to last requirements?

**Comment by agilecube** [comment] 2015-10-15 11:02
okey. Marking as "Wontfix"

**Comment by agilecube** [comment] 2015-10-15 11:05
That same bolg says that : "will happen some time this fall"

**Comment by agilecube** [comment] 2015-10-15 11:20
Please note, mobile site works perfectly on iOS 9- safari 9, just for your information.

**Closed as completed** 2015-10-19 14:43 UTC
Labels: bug, wontfix, HIGH, Not Reproduced
